// <auto-generated />
using System;
using GwendolineBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GwendolineBot.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20190711115800_music")]
    partial class music
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GwendolineBot.Database.Models.Music.Playlist", b =>
                {
                    b.Property<string>("Name")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Name");

                    b.ToTable("Playlists");
                });

            modelBuilder.Entity("GwendolineBot.Database.Models.Music.Song", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("PlaylistName");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistName");

                    b.ToTable("Song");
                });

            modelBuilder.Entity("GwendolineBot.Database.Models.RemindModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ChannelName");

                    b.Property<string>("Message");

                    b.Property<DateTime>("Time");

                    b.HasKey("Id");

                    b.ToTable("Reminders");
                });

            modelBuilder.Entity("GwendolineBot.Database.Models.Music.Song", b =>
                {
                    b.HasOne("GwendolineBot.Database.Models.Music.Playlist")
                        .WithMany("SongList")
                        .HasForeignKey("PlaylistName");
                });
#pragma warning restore 612, 618
        }
    }
}
